In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf

In [2]:
df = pd.read_csv('/Users/sachinrajput/Desktop/gen-ai-agentic-ai/AI/44_deep_learning_project/3rd, 4th -- ANN Theory , Installation/CHURN MODELING- TF_project/Churn_Modelling.csv')

In [3]:
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [4]:
X = df.iloc[:,3:-1].values
# pd.DataFrame(X)
y = df.iloc[:,-1].values

In [5]:
pd.DataFrame(X)

        0        1       2   3   4          5  6  7  8          9
0     619   France  Female  42   2        0.0  1  1  1  101348.88
1     608    Spain  Female  41   1   83807.86  1  0  1  112542.58
2     502   France  Female  42   8   159660.8  3  1  0  113931.57
3     699   France  Female  39   1        0.0  2  0  0   93826.63
4     850    Spain  Female  43   2  125510.82  1  1  1    79084.1
...   ...      ...     ...  ..  ..        ... .. .. ..        ...
9995  771   France    Male  39   5        0.0  2  1  0   96270.64
9996  516   France    Male  35  10   57369.61  1  1  1  101699.77
9997  709   France  Female  36   7        0.0  1  0  1   42085.58
9998  772  Germany    Male  42   3   75075.31  2  1  0   92888.52
9999  792   France  Female  28   4  130142.79  1  1  0   38190.78

[10000 rows x 10 columns]

In [6]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder = LabelEncoder()
X[:,2] = labelencoder.fit_transform(X[:,2])

In [7]:
pd.DataFrame(X)

        0        1  2   3   4          5  6  7  8          9
0     619   France  0  42   2        0.0  1  1  1  101348.88
1     608    Spain  0  41   1   83807.86  1  0  1  112542.58
2     502   France  0  42   8   159660.8  3  1  0  113931.57
3     699   France  0  39   1        0.0  2  0  0   93826.63
4     850    Spain  0  43   2  125510.82  1  1  1    79084.1
...   ...      ... ..  ..  ..        ... .. .. ..        ...
9995  771   France  1  39   5        0.0  2  1  0   96270.64
9996  516   France  1  35  10   57369.61  1  1  1  101699.77
9997  709   France  0  36   7        0.0  1  0  1   42085.58
9998  772  Germany  1  42   3   75075.31  2  1  0   92888.52
9999  792   France  0  28   4  130142.79  1  1  0   38190.78

[10000 rows x 10 columns]

In [8]:
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer([('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [9]:
pd.DataFrame(X)

       0    1    2    3  4   5   6          7  8  9  10         11
0     1.0  0.0  0.0  619  0  42   2        0.0  1  1  1  101348.88
1     0.0  0.0  1.0  608  0  41   1   83807.86  1  0  1  112542.58
2     1.0  0.0  0.0  502  0  42   8   159660.8  3  1  0  113931.57
3     1.0  0.0  0.0  699  0  39   1        0.0  2  0  0   93826.63
4     0.0  0.0  1.0  850  0  43   2  125510.82  1  1  1    79084.1
...   ...  ...  ...  ... ..  ..  ..        ... .. .. ..        ...
9995  1.0  0.0  0.0  771  1  39   5        0.0  2  1  0   96270.64
9996  1.0  0.0  0.0  516  1  35  10   57369.61  1  1  1  101699.77
9997  1.0  0.0  0.0  709  0  36   7        0.0  1  0  1   42085.58
9998  0.0  1.0  0.0  772  1  42   3   75075.31  2  1  0   92888.52
9999  1.0  0.0  0.0  792  0  28   4  130142.79  1  1  0   38190.78

[10000 rows x 12 columns]

In [10]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X = scaler.fit_transform(X)

In [11]:
pd.DataFrame(X)

,0,1,2,3,4,5,6,7,8,9,10,11
0,0.997204,-0.578736,-0.573809,-0.326221,-1.095988,0.293517,-1.041760,-1.225848,-0.911583,0.646092,0.970243,0.021886
1,-1.002804,-0.578736,1.742740,-0.440036,-1.095988,0.198164,-1.387538,0.117350,-0.911583,-1.547768,0.970243,0.216534
2,0.997204,-0.578736,-0.573809,-1.536794,-1.095988,0.293517,1.032908,1.333053,2.527057,0.646092,-1.030670,0.240687
3,0.997204,-0.578736,-0.573809,0.501521,-1.095988,0.007457,-1.387538,-1.225848,0.807737,-1.547768,-1.030670,-0.108918
4,-1.002804,-0.578736,1.742740,2.063884,-1.095988,0.388871,-1.041760,0.785728,-0.911583,0.646092,0.970243,-0.365276
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,0.997204,-0.578736,-0.573809,1.246488,0.912419,0.007457,-0.004426,-1.225848,0.807737,0.646092,-1.030670,-0.066419
9996,0.997204,-0.578736,-0.573809,-1.391939,0.912419,-0.373958,1.724464,-0.306379,-0.911583,0.646092,0.970243,0.027988
9997,0.997204,-0.578736,-0.573809,0.604988,-1.095988,-0.278604,0.687130,-1.225848,-0.911583,-1.547768,0.970243,-1.008643
9998,-1.002804,1.727904,-0.573809,1.256835,0.912419,0.293517,-0.695982,-0.022608,0.807737,0.646092,-1.030670,-0.125231
9999,0.997204,-0.578736,-0.573809,1.463771,-1.095988,-1.041433,-0.350204,0.859965,-0.911583,0.646092,-1.030670,-1.076370

In [12]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.20, random_state=0)

In [13]:
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(8000, 12)
(8000,)
(2000, 12)
(2000,)

In [14]:
# this is out first input layer 
ann = tf.keras.models.Sequential()
# We are creating a neural network model where layers will be added one after another in a sequence.

In [15]:
# this is our hidden layer with 6 neurons and relu activation function
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [16]:
# this is our second hidden layer with 5 neurons and relu activation function
ann.add(tf.keras.layers.Dense(units=5, activation='relu'))

In [17]:
# this is our third hidden layer with 4 neurons and relu activation function
ann.add(tf.keras.layers.Dense(units=4, activation='relu'))

In [18]:
# this is our fourth hidden layer with 3 neurons and relu activation function
ann.add(tf.keras.layers.Dense(units=3, activation='relu'))

In [19]:
# output layer with 1 neuron and sigmoid activation function
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

till this step from input layer hidden layer and output layer we call as forward-prpogation

Forward propagation = making the prediction.
Backpropagation = learning from the error and adjusting weights.

In [20]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [21]:
ann.fit(X_train,y_train,batch_size = 32,epochs = 150,validation_data=(X_test,y_test))

Epoch 1/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 708us/step - accuracy: 0.7809 - loss: 0.5614 - val_accuracy: 0.7975 - val_loss: 0.4866
Epoch 2/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 430us/step - accuracy: 0.7960 - loss: 0.4737 - val_accuracy: 0.7975 - val_loss: 0.4535
Epoch 3/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 431us/step - accuracy: 0.7960 - loss: 0.4500 - val_accuracy: 0.7975 - val_loss: 0.4383
Epoch 4/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 466us/step - accuracy: 0.7960 - loss: 0.4367 - val_accuracy: 0.7975 - val_loss: 0.4296
Epoch 5/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 427us/step - accuracy: 0.7960 - loss: 0.4281 - val_accuracy: 0.7975 - val_loss: 0.4237
Epoch 6/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 433us/step - accuracy: 0.7960 - loss: 0.4222 - val_accuracy: 0.7975 - val_loss: 0.4213
Epoch 7/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 425us/step - accuracy: 0.8129 - loss: 0.4180 - val_accuracy: 0.8265 - val_loss: 0.4159
Epoch 8/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 434us/step - accuracy: 0.8241 - loss: 0.4137 - val_accuracy: 0.8305 - val_loss: 0.4115
Epoch 9/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 405us/step - accuracy: 0.8255 - loss: 0.4099 - val_accuracy: 0.8320 - val_loss: 0.4071
Epoch 10/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 419us/step - accuracy: 0.8286 - loss: 0.4050 - val_accuracy: 0.8330 - val_loss: 0.4031
Epoch 11/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 413us/step - accuracy: 0.8300 - loss: 0.4010 - val_accuracy: 0.8355 - val_loss: 0.3970
Epoch 12/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 457us/step - accuracy: 0.8320 - loss: 0.3963 - val_accuracy: 0.8455 - val_loss: 0.3918
Epoch 13/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 420us/step - accuracy: 0.8366 - loss: 0.3911 - val_accuracy: 0.8480 - val_loss: 0.3852
Epoch 14/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 428us/step - accuracy: 0.8406 - loss: 0.3861 - val_accuracy: 0.8480 - val_loss: 0.3800
Epoch 15/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 412us/step - accuracy: 0.8410 - loss: 0.3821 - val_accuracy: 0.8395 - val_loss: 0.3828
Epoch 16/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 415us/step - accuracy: 0.8438 - loss: 0.3772 - val_accuracy: 0.8470 - val_loss: 0.3734
Epoch 17/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 408us/step - accuracy: 0.8469 - loss: 0.3713 - val_accuracy: 0.8515 - val_loss: 0.3649
Epoch 18/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 421us/step - accuracy: 0.8470 - loss: 0.3678 - val_accuracy: 0.8505 - val_loss: 0.3611
Epoch 19/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 411us/step - accuracy: 0.8511 - loss: 0.3638 - val_accuracy: 0.8510 - val_loss: 0.3584
Epoch 20/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 419us/step - accuracy: 0.8515 - loss: 0.3614 - val_accuracy: 0.8550 - val_loss: 0.3516
Epoch 21/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 410us/step - accuracy: 0.8524 - loss: 0.3588 - val_accuracy: 0.8555 - val_loss: 0.3489
Epoch 22/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 418us/step - accuracy: 0.8541 - loss: 0.3559 - val_accuracy: 0.8510 - val_loss: 0.3524
Epoch 23/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 410us/step - accuracy: 0.8535 - loss: 0.3545 - val_accuracy: 0.8575 - val_loss: 0.3437
Epoch 24/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 419us/step - accuracy: 0.8577 - loss: 0.3530 - val_accuracy: 0.8590 - val_loss: 0.3419
Epoch 25/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 404us/step - accuracy: 0.8537 - loss: 0.3516 - val_accuracy: 0.8580 - val_loss: 0.3396
Epoch 26/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 411us/step - accuracy: 0.8550 - loss: 0.3508 - val_accuracy: 0.8520 - val_loss: 0.3449
Epoch 27/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 420us/step - accuracy: 0.8587 - loss: 0.3494 - val_accuracy: 0.8600 - val_loss: 0.3372
Epoch 28/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 413us/step - accuracy: 0.8571 - loss: 0.3470 - val_accuracy: 0.8600 - val_loss: 0.3353
Epoch 29/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 437us/step - accuracy: 0.8571 - loss: 0.3464 - val_accuracy: 0.8595 - val_loss: 0.3366
Epoch 30/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 413us/step - accuracy: 0.8564 - loss: 0.3456 - val_accuracy: 0.8580 - val_loss: 0.3374
Epoch 31/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 414us/step - accuracy: 0.8589 - loss: 0.3456 - val_accuracy: 0.8570 - val_loss: 0.3372
Epoch 32/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 409us/step - accuracy: 0.8580 - loss: 0.3444 - val_accuracy: 0.8560 - val_loss: 0.3373
Epoch 33/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 414us/step - accuracy: 0.8579 - loss: 0.3438 - val_accuracy: 0.8520 - val_loss: 0.3447
Epoch 34/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 409us/step - accuracy: 0.8586 - loss: 0.3434 - val_accuracy: 0.8615 - val_loss: 0.3347
Epoch 35/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 415us/step - accuracy: 0.8589 - loss: 0.3430 - val_accuracy: 0.8555 - val_loss: 0.3391
Epoch 36/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 404us/step - accuracy: 0.8595 - loss: 0.3415 - val_accuracy: 0.8620 - val_loss: 0.3355
Epoch 37/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 559us/step - accuracy: 0.8586 - loss: 0.3416 - val_accuracy: 0.8640 - val_loss: 0.3319
Epoch 38/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 403us/step - accuracy: 0.8591 - loss: 0.3413 - val_accuracy: 0.8560 - val_loss: 0.3352
Epoch 39/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 419us/step - accuracy: 0.8599 - loss: 0.3411 - val_accuracy: 0.8610 - val_loss: 0.3328
Epoch 40/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 411us/step - accuracy: 0.8586 - loss: 0.3418 - val_accuracy: 0.8635 - val_loss: 0.3348
Epoch 41/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 420us/step - accuracy: 0.8618 - loss: 0.3405 - val_accuracy: 0.8640 - val_loss: 0.3313
Epoch 42/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 408us/step - accuracy: 0.8614 - loss: 0.3401 - val_accuracy: 0.8540 - val_loss: 0.3374
Epoch 43/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 420us/step - accuracy: 0.8615 - loss: 0.3396 - val_accuracy: 0.8625 - val_loss: 0.3314
Epoch 44/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 409us/step - accuracy: 0.8584 - loss: 0.3398 - val_accuracy: 0.8615 - val_loss: 0.3338
Epoch 45/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 418us/step - accuracy: 0.8615 - loss: 0.3389 - val_accuracy: 0.8650 - val_loss: 0.3335
Epoch 46/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 432us/step - accuracy: 0.8602 - loss: 0.3394 - val_accuracy: 0.8620 - val_loss: 0.3336
Epoch 47/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 412us/step - accuracy: 0.8608 - loss: 0.3390 - val_accuracy: 0.8540 - val_loss: 0.3438
Epoch 48/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 420us/step - accuracy: 0.8576 - loss: 0.3385 - val_accuracy: 0.8580 - val_loss: 0.3385
Epoch 49/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 410us/step - accuracy: 0.8597 - loss: 0.3392 - val_accuracy: 0.8625 - val_loss: 0.3311
Epoch 50/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 419us/step - accuracy: 0.8608 - loss: 0.3377 - val_accuracy: 0.8550 - val_loss: 0.3353
Epoch 51/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 412us/step - accuracy: 0.8610 - loss: 0.3384 - val_accuracy: 0.8610 - val_loss: 0.3311
Epoch 52/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 413us/step - accuracy: 0.8620 - loss: 0.3382 - val_accuracy: 0.8620 - val_loss: 0.3319
Epoch 53/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 408us/step - accuracy: 0.8597 - loss: 0.3390 - val_accuracy: 0.8630 - val_loss: 0.3321
Epoch 54/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 415us/step - accuracy: 0.8579 - loss: 0.3386 - val_accuracy: 0.8595 - val_loss: 0.3322
Epoch 55/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 412us/step - accuracy: 0.8618 - loss: 0.3374 - val_accuracy: 0.8465 - val_loss: 0.3513
Epoch 56/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 413us/step - accuracy: 0.8614 - loss: 0.3376 - val_accuracy: 0.8635 - val_loss: 0.3313
Epoch 57/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 414us/step - accuracy: 0.8616 - loss: 0.3372 - val_accuracy: 0.8575 - val_loss: 0.3369
Epoch 58/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 421us/step - accuracy: 0.8609 - loss: 0.3374 - val_accuracy: 0.8560 - val_loss: 0.3333
Epoch 59/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 409us/step - accuracy: 0.8577 - loss: 0.3375 - val_accuracy: 0.8645 - val_loss: 0.3311
Epoch 60/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 418us/step - accuracy: 0.8583 - loss: 0.3378 - val_accuracy: 0.8630 - val_loss: 0.3342
Epoch 61/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 403us/step - accuracy: 0.8626 - loss: 0.3367 - val_accuracy: 0.8530 - val_loss: 0.3424
Epoch 62/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 439us/step - accuracy: 0.8610 - loss: 0.3377 - val_accuracy: 0.8590 - val_loss: 0.3339
Epoch 63/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 407us/step - accuracy: 0.8602 - loss: 0.3368 - val_accuracy: 0.8555 - val_loss: 0.3339
Epoch 64/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 415us/step - accuracy: 0.8612 - loss: 0.3371 - val_accuracy: 0.8605 - val_loss: 0.3337
Epoch 65/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 405us/step - accuracy: 0.8602 - loss: 0.3365 - val_accuracy: 0.8575 - val_loss: 0.3367
Epoch 66/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 419us/step - accuracy: 0.8611 - loss: 0.3364 - val_accuracy: 0.8590 - val_loss: 0.3331
Epoch 67/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 413us/step - accuracy: 0.8626 - loss: 0.3356 - val_accuracy: 0.8580 - val_loss: 0.3327
Epoch 68/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 412us/step - accuracy: 0.8604 - loss: 0.3375 - val_accuracy: 0.8535 - val_loss: 0.3407
Epoch 69/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 417us/step - accuracy: 0.8610 - loss: 0.3369 - val_accuracy: 0.8605 - val_loss: 0.3319
Epoch 70/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 412us/step - accuracy: 0.8609 - loss: 0.3357 - val_accuracy: 0.8600 - val_loss: 0.3318
Epoch 71/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 416us/step - accuracy: 0.8610 - loss: 0.3358 - val_accuracy: 0.8645 - val_loss: 0.3326
Epoch 72/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 413us/step - accuracy: 0.8614 - loss: 0.3354 - val_accuracy: 0.8590 - val_loss: 0.3384
Epoch 73/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 416us/step - accuracy: 0.8612 - loss: 0.3360 - val_accuracy: 0.8630 - val_loss: 0.3330
Epoch 74/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 414us/step - accuracy: 0.8627 - loss: 0.3350 - val_accuracy: 0.8620 - val_loss: 0.3313
Epoch 75/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 416us/step - accuracy: 0.8635 - loss: 0.3353 - val_accuracy: 0.8590 - val_loss: 0.3326
Epoch 76/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 412us/step - accuracy: 0.8625 - loss: 0.3356 - val_accuracy: 0.8530 - val_loss: 0.3417
Epoch 77/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 426us/step - accuracy: 0.8624 - loss: 0.3358 - val_accuracy: 0.8610 - val_loss: 0.3345
Epoch 78/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 422us/step - accuracy: 0.8612 - loss: 0.3349 - val_accuracy: 0.8645 - val_loss: 0.3343
Epoch 79/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 412us/step - accuracy: 0.8625 - loss: 0.3347 - val_accuracy: 0.8580 - val_loss: 0.3352
Epoch 80/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 410us/step - accuracy: 0.8611 - loss: 0.3357 - val_accuracy: 0.8585 - val_loss: 0.3334
Epoch 81/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 420us/step - accuracy: 0.8620 - loss: 0.3347 - val_accuracy: 0.8565 - val_loss: 0.3350
Epoch 82/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 536us/step - accuracy: 0.8601 - loss: 0.3353 - val_accuracy: 0.8630 - val_loss: 0.3315
Epoch 83/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 408us/step - accuracy: 0.8612 - loss: 0.3353 - val_accuracy: 0.8615 - val_loss: 0.3326
Epoch 84/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 413us/step - accuracy: 0.8619 - loss: 0.3350 - val_accuracy: 0.8615 - val_loss: 0.3334
Epoch 85/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 414us/step - accuracy: 0.8616 - loss: 0.3347 - val_accuracy: 0.8585 - val_loss: 0.3333
Epoch 86/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 407us/step - accuracy: 0.8625 - loss: 0.3346 - val_accuracy: 0.8605 - val_loss: 0.3325
Epoch 87/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 413us/step - accuracy: 0.8621 - loss: 0.3349 - val_accuracy: 0.8525 - val_loss: 0.3395
Epoch 88/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 422us/step - accuracy: 0.8593 - loss: 0.3352 - val_accuracy: 0.8600 - val_loss: 0.3312
Epoch 89/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 405us/step - accuracy: 0.8600 - loss: 0.3347 - val_accuracy: 0.8595 - val_loss: 0.3325
Epoch 90/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 412us/step - accuracy: 0.8609 - loss: 0.3351 - val_accuracy: 0.8530 - val_loss: 0.3376
Epoch 91/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 433us/step - accuracy: 0.8624 - loss: 0.3342 - val_accuracy: 0.8605 - val_loss: 0.3354
Epoch 92/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 405us/step - accuracy: 0.8616 - loss: 0.3340 - val_accuracy: 0.8605 - val_loss: 0.3335
Epoch 93/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 411us/step - accuracy: 0.8625 - loss: 0.3347 - val_accuracy: 0.8545 - val_loss: 0.3435
Epoch 94/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 411us/step - accuracy: 0.8591 - loss: 0.3347 - val_accuracy: 0.8630 - val_loss: 0.3321
Epoch 95/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 404us/step - accuracy: 0.8619 - loss: 0.3338 - val_accuracy: 0.8475 - val_loss: 0.3456
Epoch 96/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 414us/step - accuracy: 0.8627 - loss: 0.3341 - val_accuracy: 0.8540 - val_loss: 0.3349
Epoch 97/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 412us/step - accuracy: 0.8601 - loss: 0.3343 - val_accuracy: 0.8565 - val_loss: 0.3360
Epoch 98/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 406us/step - accuracy: 0.8616 - loss: 0.3343 - val_accuracy: 0.8510 - val_loss: 0.3430
Epoch 99/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 409us/step - accuracy: 0.8633 - loss: 0.3343 - val_accuracy: 0.8525 - val_loss: 0.3392
Epoch 100/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 407us/step - accuracy: 0.8591 - loss: 0.3347 - val_accuracy: 0.8550 - val_loss: 0.3399
Epoch 101/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 413us/step - accuracy: 0.8605 - loss: 0.3345 - val_accuracy: 0.8575 - val_loss: 0.3334
Epoch 102/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 415us/step - accuracy: 0.8600 - loss: 0.3338 - val_accuracy: 0.8570 - val_loss: 0.3355
Epoch 103/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 407us/step - accuracy: 0.8614 - loss: 0.3344 - val_accuracy: 0.8595 - val_loss: 0.3316
Epoch 104/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 410us/step - accuracy: 0.8604 - loss: 0.3337 - val_accuracy: 0.8625 - val_loss: 0.3307
Epoch 105/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 432us/step - accuracy: 0.8595 - loss: 0.3348 - val_accuracy: 0.8575 - val_loss: 0.3332
Epoch 106/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 406us/step - accuracy: 0.8624 - loss: 0.3335 - val_accuracy: 0.8590 - val_loss: 0.3367
Epoch 107/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 412us/step - accuracy: 0.8608 - loss: 0.3337 - val_accuracy: 0.8620 - val_loss: 0.3321
Epoch 108/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 413us/step - accuracy: 0.8619 - loss: 0.3337 - val_accuracy: 0.8600 - val_loss: 0.3327
Epoch 109/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 415us/step - accuracy: 0.8610 - loss: 0.3329 - val_accuracy: 0.8565 - val_loss: 0.3350
Epoch 110/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 416us/step - accuracy: 0.8601 - loss: 0.3333 - val_accuracy: 0.8565 - val_loss: 0.3337
Epoch 111/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 412us/step - accuracy: 0.8606 - loss: 0.3342 - val_accuracy: 0.8545 - val_loss: 0.3373
Epoch 112/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 419us/step - accuracy: 0.8614 - loss: 0.3326 - val_accuracy: 0.8575 - val_loss: 0.3329
Epoch 113/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 417us/step - accuracy: 0.8624 - loss: 0.3326 - val_accuracy: 0.8545 - val_loss: 0.3363
Epoch 114/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 402us/step - accuracy: 0.8625 - loss: 0.3344 - val_accuracy: 0.8610 - val_loss: 0.3327
Epoch 115/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 415us/step - accuracy: 0.8626 - loss: 0.3331 - val_accuracy: 0.8580 - val_loss: 0.3339
Epoch 116/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 415us/step - accuracy: 0.8595 - loss: 0.3338 - val_accuracy: 0.8585 - val_loss: 0.3327
Epoch 117/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 407us/step - accuracy: 0.8633 - loss: 0.3328 - val_accuracy: 0.8555 - val_loss: 0.3340
Epoch 118/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 411us/step - accuracy: 0.8619 - loss: 0.3333 - val_accuracy: 0.8610 - val_loss: 0.3312
Epoch 119/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 427us/step - accuracy: 0.8610 - loss: 0.3333 - val_accuracy: 0.8580 - val_loss: 0.3322
Epoch 120/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 405us/step - accuracy: 0.8605 - loss: 0.3336 - val_accuracy: 0.8520 - val_loss: 0.3383
Epoch 121/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 546us/step - accuracy: 0.8610 - loss: 0.3336 - val_accuracy: 0.8615 - val_loss: 0.3324
Epoch 122/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 410us/step - accuracy: 0.8602 - loss: 0.3336 - val_accuracy: 0.8590 - val_loss: 0.3381
Epoch 123/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 412us/step - accuracy: 0.8600 - loss: 0.3332 - val_accuracy: 0.8620 - val_loss: 0.3300
Epoch 124/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 413us/step - accuracy: 0.8636 - loss: 0.3330 - val_accuracy: 0.8435 - val_loss: 0.3502
Epoch 125/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 403us/step - accuracy: 0.8619 - loss: 0.3336 - val_accuracy: 0.8585 - val_loss: 0.3378
Epoch 126/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 407us/step - accuracy: 0.8591 - loss: 0.3330 - val_accuracy: 0.8610 - val_loss: 0.3323
Epoch 127/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 416us/step - accuracy: 0.8611 - loss: 0.3337 - val_accuracy: 0.8590 - val_loss: 0.3357
Epoch 128/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 410us/step - accuracy: 0.8630 - loss: 0.3329 - val_accuracy: 0.8620 - val_loss: 0.3319
Epoch 129/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 416us/step - accuracy: 0.8610 - loss: 0.3333 - val_accuracy: 0.8595 - val_loss: 0.3322
Epoch 130/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 405us/step - accuracy: 0.8622 - loss: 0.3327 - val_accuracy: 0.8550 - val_loss: 0.3369
Epoch 131/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 415us/step - accuracy: 0.8615 - loss: 0.3331 - val_accuracy: 0.8630 - val_loss: 0.3297
Epoch 132/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 406us/step - accuracy: 0.8614 - loss: 0.3336 - val_accuracy: 0.8570 - val_loss: 0.3337
Epoch 133/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 434us/step - accuracy: 0.8622 - loss: 0.3332 - val_accuracy: 0.8600 - val_loss: 0.3313
Epoch 134/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 405us/step - accuracy: 0.8608 - loss: 0.3335 - val_accuracy: 0.8595 - val_loss: 0.3332
Epoch 135/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 417us/step - accuracy: 0.8624 - loss: 0.3332 - val_accuracy: 0.8585 - val_loss: 0.3340
Epoch 136/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 404us/step - accuracy: 0.8619 - loss: 0.3331 - val_accuracy: 0.8580 - val_loss: 0.3362
Epoch 137/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 411us/step - accuracy: 0.8589 - loss: 0.3340 - val_accuracy: 0.8580 - val_loss: 0.3335
Epoch 138/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 408us/step - accuracy: 0.8639 - loss: 0.3328 - val_accuracy: 0.8600 - val_loss: 0.3317
Epoch 139/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 412us/step - accuracy: 0.8616 - loss: 0.3331 - val_accuracy: 0.8605 - val_loss: 0.3313
Epoch 140/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 407us/step - accuracy: 0.8627 - loss: 0.3333 - val_accuracy: 0.8595 - val_loss: 0.3341
Epoch 141/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 412us/step - accuracy: 0.8614 - loss: 0.3329 - val_accuracy: 0.8565 - val_loss: 0.3324
Epoch 142/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 404us/step - accuracy: 0.8600 - loss: 0.3332 - val_accuracy: 0.8620 - val_loss: 0.3309
Epoch 143/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 418us/step - accuracy: 0.8614 - loss: 0.3334 - val_accuracy: 0.8600 - val_loss: 0.3333
Epoch 144/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 413us/step - accuracy: 0.8611 - loss: 0.3334 - val_accuracy: 0.8595 - val_loss: 0.3332
Epoch 145/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 418us/step - accuracy: 0.8618 - loss: 0.3333 - val_accuracy: 0.8590 - val_loss: 0.3334
Epoch 146/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 433us/step - accuracy: 0.8599 - loss: 0.3329 - val_accuracy: 0.8600 - val_loss: 0.3319
Epoch 147/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 410us/step - accuracy: 0.8621 - loss: 0.3330 - val_accuracy: 0.8530 - val_loss: 0.3363
Epoch 148/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 411us/step - accuracy: 0.8612 - loss: 0.3330 - val_accuracy: 0.8540 - val_loss: 0.3377
Epoch 149/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 412us/step - accuracy: 0.8612 - loss: 0.3334 - val_accuracy: 0.8560 - val_loss: 0.3330
Epoch 150/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 409us/step - accuracy: 0.8631 - loss: 0.3331 - val_accuracy: 0.8595 - val_loss: 0.3330

In [22]:
y_pred = ann.predict(X_test)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 492us/step

In [23]:
y_pred

array([[0.27268717],
       [0.28189203],
       [0.11226863],
       ...,
       [0.23197004],
       [0.10884126],
       [0.2667068 ]], shape=(2000, 1), dtype=float32)

In [24]:
pd.DataFrame(y_pred, columns=['Predicted_Probability']).head()

   Predicted_Probability
0               0.272687
1               0.281892
2               0.112269
3               0.077817
4               0.072181

In [25]:
pd.DataFrame(y_test, columns=['Actual_Probability']).head()

   Actual_Probability
0                   0
1                   1
2                   0
3                   0
4                   0

In [26]:
y_pred = (y_pred > 0.5)

In [27]:
pd.DataFrame(y_pred, columns=['Predicted_Binary']).head(10)

   Predicted_Binary
0             False
1             False
2             False
3             False
4             False
5              True
6             False
7             False
8             False
9              True

In [28]:
from sklearn.metrics import confusion_matrix, accuracy_score

ac = accuracy_score(y_test,y_pred)

In [29]:
ac

0.8595

In [30]:
cm = confusion_matrix(y_test,y_pred)

In [32]:
cm

array([[1515,   80],
       [ 201,  204]])